name: Cloudflare Pages PR Preview with Comment

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: 📦 Install wrangler
        run: npm install -g wrangler

      - name: 🚀 Deploy to Cloudflare Pages (Preview)
        run: |
          wrangler pages deploy ./out \
            --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }} \
            --branch=pr-${{ github.event.pull_request.number }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Post preview URL as PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 **Cloudflare Pages Preview URL:**  
            https://${{ secrets.CLOUDFLARE_PROJECT_NAME }}--pr-${{ github.event.pull_request.number }}.${{ secrets.CLOUDFLARE_ACCOUNT_NAME }}.pages.dev
